export default {
  sex: { displayName: "Gender", isCategorical: true, unit: "", type: "String" },
  age: { displayName: "Age", isCategorical: false, unit: "", type: "Number" },
  bloodGlucose: {
    displayName: "Blood Glucose",
    isCategorical: false,
    unit: "(mg/dL)",
    type: "Number",
  },
  diastolicBloodPressure: {
    displayName: "Diastolic Blood Pressure",
    isCategorical: false,
    unit: "(mm Hg)",
    type: "Number",
  },
  drinks: {
    displayName: "Drinks?",
    isCategorical: true,
    unit: "",
    type: "String",
  },
  hdlCholestrol: {
    displayName: "Good Cholestrol",
    isCategorical: false,
    unit: "(mg/dL)",
    type: "Number",
  },
  hearLeft: {
    displayName: "Left Hearing",
    isCategorical: true,
    unit: "",
    type: "String",
  },
  hearRight: {
    displayName: "Right Hearing",
    isCategorical: true,
    unit: "",
    type: "String",
  },
  height: {
    displayName: "Height",
    isCategorical: false,
    unit: "(cm)",
    type: "Number",
  },
  hemoglobin: {
    displayName: "Hemoglobin",
    isCategorical: false,
    unit: "(g/dL)",
    type: "Number",
  },
  ldlCholestrol: {
    displayName: "Bad Cholestrol",
    isCategorical: false,
    unit: "(mg/dL)",
    type: "Number",
  },
  serumCreatinine: {
    displayName: "Serum Creatinine",
    isCategorical: false,
    unit: "(mg/dL)",
    type: "Number",
  },
  sightLeft: {
    displayName: "Left Eye Sight",
    isCategorical: false,
    unit: "",
    type: "Number",
  },
  sightRight: {
    displayName: "Right Eye Sight",
    isCategorical: false,
    unit: "",
    type: "Number",
  },
  smokes: {
    displayName: "Smokes?",
    isCategorical: true,
    unit: "",
    type: "String",
  },
  systolicBloodPressure: {
    displayName: "Systolic Blood Pressure",
    isCategorical: false,
    unit: "(mm Hg)",
    type: "Number",
  },
  totalCholestrol: {
    displayName: "Total Cholestrol",
    isCategorical: false,
    unit: "(mg/dL)",
    type: "Number",
  },
  triglyceride: {
    displayName: "Triglyceride",
    isCategorical: false,
    unit: "(mg/dL)",
    type: "Number",
  },
  urineProtein: {
    displayName: "Urine Protein",
    isCategorical: true,
    unit: "",
    type: "Number",
  },
  waistline: {
    displayName: "Waistline",
    isCategorical: false,
    unit: "(cm)",
    type: "Number",
  },
  weight: {
    displayName: "Weight",
    isCategorical: false,
    unit: "(kg)",
    type: "Number",
  },
};
