metadata = {
  'sex': { 'displayName': "Gender", 'isCategorical': True, 'unit': "", 'type': "String" },
  'age': { 'displayName': "Age", 'isCategorical': False, 'unit': "", 'type': "Number" },
  'bloodGlucose': {
    'displayName': "Blood Glucose",
    'isCategorical': False,
    'unit': "(mg/dL)",
    'type': "Number",
  },
  'diastolicBloodPressure': {
    'displayName': "Diastolic Blood Pressure",
    'isCategorical': False,
    'unit': "(mm Hg)",
    'type': "Number",
  },
  'drinks': {
    'displayName': "Drinks?",
    'isCategorical': True,
    'unit': "",
    'type': "String",
  },
  'hdlCholestrol': {
    'displayName': "Good Cholestrol",
    'isCategorical': False,
    'unit': "(mg/dL)",
    'type': "Number",
  },
  'hearLeft': {
    'displayName': "Left Hearing",
    'isCategorical': True,
    'unit': "",
    'type': "String",
  },
  'hearRight': {
    'displayName': "Right Hearing",
    'isCategorical': True,
    'unit': "",
    'type': "String",
  },
  'height': {
    'displayName': "Height",
    'isCategorical': False,
    'unit': "(cm)",
    'type': "Number",
  },
  'hemoglobin': {
    'displayName': "Hemoglobin",
    'isCategorical': False,
    'unit': "(g/dL)",
    'type': "Number",
  },
  'ldlCholestrol': {
    'displayName': "Bad Cholestrol",
    'isCategorical': False,
    'unit': "(mg/dL)",
    'type': "Number",
  },
  'serumCreatinine': {
    'displayName': "Serum Creatinine",
    'isCategorical': False,
    'unit': "(mg/dL)",
    'type': "Number",
  },
  'sightLeft': {
    'displayName': "Left Eye Sight",
    'isCategorical': False,
    'unit': "",
    'type': "Number",
  },
  'sightRight': {
    'displayName': "Right Eye Sight",
    'isCategorical': False,
    'unit': "",
    'type': "Number",
  },
  'smokes': {
    'displayName': "Smokes?",
    'isCategorical': True,
    'unit': "",
    'type': "String",
  },
  'systolicBloodPressure': {
    'displayName': "Systolic Blood Pressure",
    'isCategorical': False,
    'unit': "(mm Hg)",
    'type': "Number",
  },
  'totalCholestrol': {
    'displayName': "Total Cholestrol",
    'isCategorical': False,
    'unit': "(mg/dL)",
    'type': "Number",
  },
  'triglyceride': {
    'displayName': "Triglyceride",
    'isCategorical': False,
    'unit': "(mg/dL)",
    'type': "Number",
  },
  'urineProtein': {
    'displayName': "Urine Protein",
    'isCategorical': True,
    'unit': "",
    'type': "Number",
  },
  'waistline': {
    'displayName': "Waistline",
    'isCategorical': False,
    'unit': "(cm)",
    'type': "Number",
  },
  'weight': {
    'displayName': "Weight",
    'isCategorical': False,
    'unit': "(kg)",
    'type': "Number",
  },
}